---
- name: Upgrade ios Router Firmware
  hosts: ios
  connection: network_cli
  gather_facts: no
  vars:
    desired_ios_version: "16.08.01b"

  tasks:
    - name: GATHER ROUTER FACTS
      ios_facts:
        gather_subset: all

    - name: create HTML report
      template:
        src: ./templates/ios/report-ios.j2
        dest: /tmp/inventory_report_ios.html
      delegate_to: localhost
      run_once: true
