---
- name: Backup running-config on routers
  hosts: ios
  gather_facts: false
  connection: local
  tasks:
  - name: run show commands
    telnet:
      user: alex
      password: Ab123456
      login_prompt: "Username: "
      prompts:
        - "[>#]"
    register: print_output
  - name: save output to a file
    copy:
      content: "{{ print_output.stdout[0] }}"
      dest: "./output/{{ inventory_hostname }}.txt"
