---
- name: Backup running-config on routers
  hosts: ios
  gather_facts: false
  connection: local
  tasks:
    - name: Ansible date fact example
      debug:
        var=ansible_date_time.date
    - name: Get running config
      ios_command:
        commands: show run
      register: show_run
    - name: Save config to file
      copy:
        content: "{{ show_run.stdout[0] }}"
        dest: "./output/{{inventory_hostname}}-{{ansible_date_time.date}}.txt"
