---
- name: Backup running-config on routers
  hosts: all
  gather_facts: false
  connection: local
  tasks:
  - name: Backup the current config
    authorize: "yes"
    ios_command:
      commands: show run
    register: print_output
  - name: save output to a file
    copy: content="{{ print_output.stdout[0] }}" dest="./output/{{ inventory_hostname }}.txt"
