---

- import_playbook: get_vrfs.yml

- hosts: cisco_xe
  gather_facts: False

  vars:
    ip_arp_output: []

  roles:
    - ansible-network.network-engine

  tasks:

    - name: "Ansible | List all known variables and facts"
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 1

    - name: List just the vrfs in the vrf_list variable from the get_vrfs playbook
      debug: var=vrf_list

    - name: Execute show ip arp show command on default VRF
      ios_command:
        commands: " show ip arp"
      register: output0

    - name: Execute custom show ip arp vrf <vrf> command
      ios_command:
        commands: " show ip arp vrf {{ item }} "
      with_items:
        - "{{ vrf_list }}"
      register: output1
      ignore_errors: yes

    - name: Display the DEFAULT output
      debug:
        msg:
          "{{ output0.stdout_lines }}"


    - name: Display the VRF output
      debug:
        msg:  "{{ item.stdout_lines }}"
      with_items:
        - "{{ output1.results.0 }}"
