---

- name: Pull show commands form Cisco IOS
  hosts: ios

  gather_facts: False
  ignore_errors: yes

# The commented lines show the pre Ansible 2.5 method of passing credentials to network modules using the "provider"
# method.  In Ansible 2.5 the network_cli connection method was introduced in order to better align network
# and server modules so they behave in a more consistent manner.

#  connection: local
#  vars:
#    cli:
#        host: "{{ inventory_hostname }}"
#        username: "{{ ansible_user }}"
#        password: "{{ ansible_password }}"
#        port: "{{ ansible_port }}"
#        timeout: 30

  tasks:
    - name: Iterate over show commands
      ios_command:
        commands: "{{ item }}"
#        provider: "{{ cli }}"

      with_items:
      - "show run"
      - "show version"
      - "show inventory"
      - "show ip int br"
      - "show ip route"

      register: output

    - debug: var=output

    # Save the raw output which is an unformatted data structure
    - local_action: copy content="{{ output.results }}" dest="./logs/{{ inventory_hostname }}-raw-output.txt"
    # Sae the configuration only in the commonly formatted file
    - local_action: copy content="{{ output.results.0.stdout.0 }}" dest="./logs/{{ inventory_hostname }}-config.txt"

    # Run the output through a Jinja2 template to get all the show commands in their common format
    - name: Generate Device Show Command File(s)
      template: src=./templates/show-commands-template.j2
                  dest=./logs/{{ inventory_hostname }}-readable-show-output.txt
      with_items:
        - "{{ output }}"
