---

- hosts: cisco_xe
  connection: local
  become: yes
  gather_facts: False

  vars:
    cli:
        host: "{{ inventory_hostname }}"
        username: "{{ v_username }}"
        password: "{{ v_password }}"
        authorize: yes
        auth_pass: "{{ v_password }}"

  tasks:
    - name: Get Vault Variables
      include_vars: ./group_vars/creds.yml
    - name: Get Device Show Command List
      include_vars: ./group_vars/ios_cmdlist.yml
    - name: Execute Show Commands on Cisco IOS Devices
      ios_command:
        commands: "{{ item }} "
        provider: "{{ cli }} "
      with_items:
          - "{{ ios_show_commands }}"
      register: output
      ignore_errors: yes

    - name: Debug with -v to show output contents only when debugging
      debug:
        var: output
        verbosity: 1

    - local_action: copy content="{{ output | to_nice_json }}" dest="./logs/{{ inventory_hostname }}.json"

    - name: Generate Device Show Command File(s)
      template: src=./templates/show-commands-template.j2
                  dest=./logs/{{ inventory_hostname }}.show-commands.txt

      with_items:
        - "{{ output }}"
